services:
  app:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    image: api-laravel-app
    container_name: api_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - api-network

  web:
    image: nginx:alpine
    container_name: api_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-network
    depends_on:
      - app

  # Servicio Worker con Supervisor
  queue:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    # Aquí está el cambio: ejecutamos supervisord en lugar de php artisan
    command: "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    volumes:
      - ./:/var/www
    networks:
      - api-network
    depends_on:
      - app

networks:
  api-network:
    driver: bridge
